// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Synaplic.Inventory.Domain.Entities;
using Synaplic.Inventory.Domain.Entities.Inventory;
using Synaplic.Inventory.Infrastructure.Contexts;

namespace Synaplic.Inventory.Infrastructure.Contexts
{
    public partial class UniContext
    {

        public UniContext(DbContextOptions<UniContext> options)
            : base(options)
        {
        }

 



        public DbSet<InventorySession> InventorySessions { get; set; }
        public DbSet<InventoryScan> InventoryScans { get; set; }
        public DbSet<InventoryStock> InventoryStocks { get; set; }


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            OnIdentityModelCreating(modelBuilder);




            modelBuilder.Entity<InventorySession>(entity =>
            {
                entity.ToTable("InventorySession");
                //entity.Property(e => e.DateDebut).HasColumnType("DateTime2");
                //entity.Property(e => e.DateDebutPrevisionnel).HasColumnType("DateTime2");
                //entity.Property(e => e.DateFin).HasColumnType("DateTime2");

                entity.Property(e => e.Designation).HasMaxLength(250);

                entity.Property(e => e.Status)
                    .IsRequired()
                    .HasColumnType("int");
            });


            modelBuilder.Entity<InventoryStock>(entity =>
            {
                entity.ToTable("InventoryStock");

                entity.Property(e => e.CodeArticle).HasMaxLength(70);
                entity.Property(e => e.Designation).HasMaxLength(70);
                entity.Property(e => e.Famille).HasMaxLength(70);

               

                entity.HasOne(d => d.InventorySession)
                    .WithMany(p => p.InventoryStocks)
                    .HasForeignKey(d => d.SessionId)
                    .OnDelete(DeleteBehavior.NoAction)
                    .HasConstraintName("FK_InventorySession_Stocks");


            });

            modelBuilder.Entity<InventoryScan>(entity =>
            {
                entity.ToTable("InventoryScan");

                entity.Property(e => e.CodeArticle).HasMaxLength(70);

                entity.HasOne(d => d.InventorySession)
                    .WithMany(p => p.InventoryScans)
                    .HasForeignKey(d => d.SessionId)
                    .OnDelete(DeleteBehavior.NoAction)
                    .HasConstraintName("FK_InventorySession_Scans");


            });


            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}